name: 'DQN'
params:
  replay_buffer_size: 1000000
  low_level_actions: 8  # w
  batch_size: 64
  discount: 0.9
  #target_net_updates: 1000
  tau: 0.999
  double_dqn: False
  epsilon_start: 0.9
  epsilon_end: 0.05
  epsilon_decay: 20000  # number of learning steps for half epsilon, set to 0 if no decay is needed
  learning_rate: 0.001
  hidden_units: [140, 140]
  device: 'cpu'  # "cuda", "cpu"
  load_nets: ''
  load_buffers: ''
trainable_params: ''
