name: 'SplitDynamicsModelPoseLSTM'
params:
  hidden_units: [10, 10]
  n_layers: [2, 2]
  learning_rate: [0.001, 0.001]
  batch_size: [64, 64]
  loss: ['mse', 'mse']  # Options: 'mse', 'huber'
  n_epochs: [40, 40]

  state_dim: 2120
  action_dim: 16
  device: 'cpu'  # "cuda", "cpu"
trainable_params: ''
