name: 'SplitDynamicsModelFeature'
params:
  hidden_units: [[100, 100], [100, 100]]
  learning_rate: [0.001, 0.001]
  batch_size: [128, 128]
  loss: ['mse', 'mse']  # Options: 'mse', 'huber'
  n_epochs: [40, 40]

  state_dim: 2120
  action_dim: 16
  device: 'cpu'  # "cuda", "cpu"
trainable_params: ''
